

services:
  spartan_spark_submit:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: spartan_spark_submit
    ports:
      - "18080:18080"
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - ${WORKSPACE_LOCATION}:/home/glue_user/workspace/
      - ${STORAGE_LOCATION}:/home/glue_user/workspace/storage/core/
    environment:
      AWS_PROFILE: ${PROFILE_NAME}
      DISABLE_SSL: "true"
    env_file:
      - .env
    command: spark-submit /home/glue_user/workspace/${SCRIPT_FILE_NAME} --JOB_NAME ${JOB_NAME}
    restart: "no"

  spartan_test:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: spartan_pytest
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - ${WORKSPACE_LOCATION}:/home/glue_user/workspace/
      - ${STORAGE_LOCATION}:/home/glue_user/workspace/storage/core/
    environment:
      AWS_PROFILE: ${PROFILE_NAME}
      DISABLE_SSL: "true"
    env_file:
      - .env
    command: -c "python3 -m pytest -vv"
    restart: "no"
