[testenv:lint]
deps =
    flake8>=6.1.0
    isort>=5.12.0
    black>=23.9.1
skip_install = true
commands =
    poetry install --with dev
    flake8 app/ tests/ --exclude=app/exceptions/__init__.py
    isort --check-only --diff app/ tests/
    black --check --diff app/ tests/

[testenv:format]
deps =
    isort>=5.12.0
    black>=23.9.1
    autoflake>=2.2.1
    autopep8>=2.3.1
skip_install = true
commands =
    poetry install --with dev
    autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables app/ tests/
    autopep8 --in-place --recursive --select=E266,E402,E501 app/ tests/
    isort app/ tests/
    black app/ tests/
